# Please see the following for configuration options:
#   https://github.com/bbatsov/rubocop
#   https://github.com/nevir/rubocop-rspec
require: rubocop-rspec

AllCops:
  Exclude:
    - rubygems*/
    - united_states.gemspec
  TargetRubyVersion: 2.1

Documentation:
  Exclude:
    - spec/**/*_spec.rb

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - .rubocop.yml
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Exclude:
    - spec/**/*_spec.rb

RSpec/DescribeClass:
  Exclude:
    - spec/support/**/*
